# vim ft=yaml
# Build some standard python wheels for the travis worker
language: python
env:
    global:
       # List packages you want to build here, maybe with versions
       # e.g "numpy scipy matplotlib==1.3.1 ipython"
       - TO_BUILD="nibabel"
       # Optional whitespace-separated list of pip specifications of where sources
       # should be found, where element of "pypi" defaults to fetching source
       # from pypi, and an empty or unset string defaults to all "pypi" elements.
       # - SOURCES="git+https://github.com/PyMVPA/PyMVPA.git@debian/2.4.0.1-1"
       # Any Python packages that need installing before you build the wheels
       # - PRE_BUILD="cython"
       # Override default numpy version for packages needing numpy
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
install:
    - sudo apt-get update -q
    - export WHEELHOUSE=$PWD/wheelhouse
    # Set base numpy version for packages requiring numpy
    # Allow override by setting global variable NUMPY_VERSION
    - |
      if [ -z $NUMPY_VERSION ]; then
        export NUMPY_VERSION=1.7.2
      fi;
    - pip install -U pip
    - python travis_install.py
script:
    - for pkg in $TO_BUILD; do
        pip install --no-index -f $WHEELHOUSE $pkg;
        python -c 'import numpy; numpy.show_config()';
      done
before_deploy:
- cd $WHEELHOUSE
- ls .
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
      secure: "ilWZL8wbTP/DNDMQgIsD2UfFOwofhEVqjiejyfM+/J9HcbKpzB08G5a1HIlT/mN1bmbVwXZLhhGGUg7U2XHdpBgCW3JEN8bRVj4MnIaG6Uu+cobPyV85YBmhN7tZPHhDoW2BHqi6wP96PdSCCVGD6S86/IGhSnUDLL7IG3VdgIw="
  region: ORD
  container: travis_wheels
  skip_cleanup: true
